{{- $name := include "authorization-api.fullname" . -}}

apiVersion: v1
kind: Secret
metadata:
  name: "secret-{{ $name }}"
  labels:
    app: {{ template "authorization-api.name" . }}
    chart: {{ template "authorization-api.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data: {}