name: E2E Test Deployment

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: sandbox
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1

      - name: Authenticate with Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy AZD
        run: |
          # Install AZD
          curl -fsSL https://aka.ms/install-azd.sh | bash
          cd ./foundationallm/deploy/starter
          az storage azcopy blob download --container azd-resources --account-name fllme2etestingresources -s ".azure/" -d ".azure/" --recursive
          azd up
