name: OIDC Test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: sandbox
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
          audience: api://FoundationaLLM-E2E

      - name: Run Test
        env:
          FoundationaLLM_AppConfig_ConnectionString: ${{ secrets.APPCONFIG_CONNECTION_STRING }}
        run: dotnet test --filter "FullyQualifiedName=FoundationaLLM.Core.Examples.Example0001_FoundationaLLMAgentInteraction.RunAsync" ./tests/dotnet/Core.Examples/Core.Examples.csproj
